# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 06:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator])),
                ('director', models.CharField(max_length=100)),
                ('imdb_score', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator])),
                ('genre', models.ManyToManyField(to='movies.Genre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
